services:
  landing-page-web-server:
    build:
      context: web
    container_name: web_server
    volumes:
      - ../frontend/dist:/var/www/frontend:ro
      - ./web/ngnix-server-VPS.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - proxy_manager_default

networks:
  proxy_manager_default:
    name: proxy_manager_default
    external: true
